---

services:
  openvpn-admin:
    build: .
    container_name: openvpn-admin
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /var/log/openvpn:/var/log/openvpn:rw  # Mounting OpenVPN logs into a container
      - ./data:/app/data:rw  # Persist application state files (ensure UID 1000 has write access)
    #ports:
    #  - 5000:5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openvpn.entrypoints=http"
      - "traefik.http.routers.openvpn.rule=Host(`${OPENVPN_DOMAIN:-localhost}`)"
      - "traefik.http.middlewares.openvpn-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.openvpn.middlewares=openvpn-https-redirect"
      - "traefik.http.routers.openvpn-secure.entrypoints=https"
      - "traefik.http.routers.openvpn-secure.rule=Host(`${OPENVPN_DOMAIN:-localhost}`)"
      - "traefik.http.routers.openvpn-secure.middlewares=traefik-auth"   # Authentification
      - "traefik.http.routers.openvpn-secure.tls=true"
      - "traefik.http.routers.openvpn-secure.service=openvpn"
      - "traefik.http.services.openvpn.loadbalancer.server.port=5000"

      # NEW: local middleware (credentials from .env)
      - "traefik.http.middlewares.openvpn-user-auth.basicauth.users=${OPENVPN_BASIC_AUTH}"
      # attach it to https router
      - "traefik.http.routers.openvpn-secure.middlewares=openvpn-user-auth"

      - "traefik.docker.network=proxy"
    networks:
      - proxy

networks:
  proxy:
    external: true
