---

services:
  openvpn-admin:
    build: .
    container_name: openvpn-admin
    environment:
      OPENVPN_MONITOR_TZ: "Europe/Bucharest"
      OPENVPN_STATUS_LOG: "/var/log/openvpn/status.log"
      OPENVPN_HISTORY_LOG: "./data/session_history.json"
      OPENVPN_ACTIVE_SESSIONS: "./data/active_sessions.json"
      OPENVPN_SERVER_STATUS: "./data/server_status.json"
      OPENVPN_CLIENT_GEO_DB: "./data/client_geolocation.json"
    volumes:
      - /var/log/openvpn:/var/log/openvpn:rw  # Mounting OpenVPN logs into a container
      - ./data:/app/data:rw  # Persist application state files
    #ports:
    #  - 5000:5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openvpn.entrypoints=http"
      - "traefik.http.routers.openvpn.rule=Host(`openvpn.nuvosys.eu`)"
#      - "traefik.http.middlewares.openvpn-auth.basicauth.users=scuruci:$$apr1$$x.lN5PaD$$bKTbjAv.Z0KLTKA.VMFNp/" # Auth
#      - "traefik.http.middlewares.openvpn-auth.basicauth.users=openvpn:$$apr1$$AxHp9Acv$$so9EImC8Jv7YULdyknjHQ., scuruci:$$apr1$$x.lN5PaD$$bKTbjAv.Z0KLTKA.VMFNp/"
      - "traefik.http.middlewares.openvpn-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.openvpn-auth.basicauth.removeheader=false"
      - "traefik.http.routers.openvpn.middlewares=openvpn-https-redirect"
      - "traefik.http.routers.openvpn-secure.entrypoints=https"
      - "traefik.http.routers.openvpn-secure.rule=Host(`openvpn.nuvosys.eu`)"
      - "traefik.http.routers.openvpn-secure.middlewares=traefik-auth"   # Authentification
      - "traefik.http.routers.openvpn-secure.tls=true"
      - "traefik.http.routers.openvpn-secure.service=openvpn"
      - "traefik.http.services.openvpn.loadbalancer.server.port=5000"

      # NEW: локальный middleware
      - "traefik.http.middlewares.openvpn-user-auth.basicauth.users=openvpn:$$apr1$$AxHp9Acv$$so9EImC8Jv7YULdyknjHQ."
      # подвесить его на https-роутер
      - "traefik.http.routers.openvpn-secure.middlewares=openvpn-user-auth"

      - "traefik.docker.network=proxy"
    networks:
      - proxy

networks:
  proxy:
    external: true
