name: Deploy via SSH

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # passphrase: ${{ secrets.SSH_PASSPHRASE }}   # если ключ с паролем
          script_stop: true
          # можно зафиксировать host key (безопаснее):
          # host_key: ${{ secrets.SSH_HOST_FINGERPRINT }}
          script: |
            set -e
            cd /home/app_data/docker/openvpn-monitor
            git pull
            docker compose pull
            docker compose up -d --remove-orphans
            echo "✅ Deploy finished"
